### ISSUE TITLE
Wireframe of main view

### ISSUE THREAD

**Issue by smileydts** [smileydts/death-or-glory#1]
Figma wireframe of the main view of the board

**Comment by djpace14** [comment]
Here is a link for a preliminary wireframe. Not sure it's the right way to do this but I think you'll get a sense of what I'm thinking.

https://www.figma.com/file/Tn7CmVx5gf4HSQAxtA0PEi/Death-or-Glory?type=design&node-id=2%3A2&mode=design&t=ff9EprJfcc4eIlFd-1

**Comment by smileydts** [comment]
Would it be good to have a sort of view of the other players?  Like to give the feel of sitting around a table so you can visualize the order of play and how many cards they have in their hand.

**Comment by djpace14** [comment]
Hmm... you mean like what they had on those old online poker games?

Would it be enough to just see their usernames and number of cards?

**Comment by smileydts** [comment]
I think so.  Maybe instead of having S&D and prestige trackers separately,
you see that info near or overlaid somehow with each other player.

**Comment by smileydts** [comment]
Eventually you see some sort of avatar connected to what kind of band they
are.

**Comment by djpace14** [comment]
Ok. Do you think this is something we should try to implement from the start or should we stick with the more simplified version to begin with?

**Comment by smileydts** [comment]
Imo if you like the concept, it could be wireframed up now.  I think you
can put anything in the wireframe that you would eventually like to see,
even if it's far away from something we'd actually implement.

**Comment by smileydts** [comment]
As long as it's within the realm of feasibility, i.e. no like voice chat or
ability to exchange crypto or whatever.

**Comment by djpace14** [comment]
Haha. So no Death or Glory token...???

**Comment by djpace14** [comment]
But sounds good. I'll maybe create a duplicate version of the main window that reflects this idea.

**Comment by smileydts** [comment]
Assuming you like the idea.  I was thinking that in order to simulate the
board game experience I would want to expand on the tabletop-like setup you
already have by perhaps positioning the players around the table.  That
neatly conveys to me who my opponents are, what their score is, and whose
turn is next.

**Comment by djpace14** [comment]
https://www.figma.com/file/Tn7CmVx5gf4HSQAxtA0PEi/Death-or-Glory?type=design&node-id=29%3A3&mode=design&t=s94TAnoYpawyd4Q8-1

Take a look at the Main Window Alternate Version 

Would you say this is a rough approximation of what you might be talking about?

**Comment by smileydts** [comment]
Yeah that's what I had in mind. What do you think?

**Comment by djpace14** [comment]
I think it could work. I suppose it does make sense and does better at trying to replicate what is lost going from tabletop to digital. We can take this approach.
