### ISSUE TITLE
Clone the repo locally

### ISSUE THREAD

**Issue by smileydts** [smileydts/death-or-glory#4]
Be able to see the project on our local machines.  Ideally do this with SSH.

**Comment by smileydts** [comment]
@djpace14

Open a terminal and run `ssh-keygen -t ed25519 -C "your_email@example.com"`
I accepted the default file path and didn't add a passphrase.
This should create 2 files: a public key and a private key.  The public key you can share with websites such as github.  The private key you just store on your machine.  Go to https://github.com/settings/keys and add a new SSH key which is your public key.  It's in the file with the PUB extension and looks something like `ssh-ed25519 [long string of characters] your@email.com`  Copy the entire contents of the file (which is your public key) to github.
Test your connection `ssh -T git@github.com`  Say yes to any warnings.  You should get your username back.

To clone and work on the repo locally, you'll have to install git.  You can get it from https://git-scm.com/
Then you can clone the repo using SSH by opening VS Code and choosing "clone git repository" on the home screen.  Use the link from the github repo for SSH.

**Comment by smileydts** [comment]
@djpace14 If you can install Docker on your machine ( https://docs.docker.com/ ) then tonight we can go over how to use it and review a pull request (new feature).

**Comment by djpace14** [comment]
So a question... When I enter this am I supposed to put in my email here?

ssh-keygen -t ed25519 -C "your_email@example.com"

**Comment by smileydts** [comment]
Yeah put your actual email there.

**Comment by djpace14** [comment]
What should I do here?

![Screenshot 2024-01-02 162301](https://github.com/smileydts/death-or-glory/assets/154949313/aa504029-bd66-48a5-a103-9d810b476748)

**Comment by smileydts** [comment]
Press enter to accept the default path.

**Comment by djpace14** [comment]
Ok. Got it

**Comment by djpace14** [comment]
![image](https://github.com/smileydts/death-or-glory/assets/154949313/eeb29f98-c84d-4be4-a1cb-d26e7e126fd9)

I think it worked

**Comment by djpace14** [comment]
When I install git which should i choose as my default editor? Visual Studio Code?

**Comment by smileydts** [comment]
Yeah
