### ISSUE TITLE
Hello World webpage from server

### ISSUE THREAD

**Issue by smileydts** [smileydts/death-or-glory#5]
Have a webpage with a button that when you click it, fetches the text "Hello World!" from an API call and displays it.

Blocked by #2

**Comment by smileydts** [comment]
@djpace14 I did something dumb and accidentally committed my changes to `main` instead of the feature branch.  Once I pushed the changes, it was more trouble than it was worth to revert :(   Apparently as an administrator, I can bypass the merge-by-PR-only requirement, which I didn't mean to do.  As a result there's no PR for this feature, as the changes are already in `main`.

Nevertheless, you can test the changes by pulling the latest on the main branch:

1. `git checkout main && git pull`
2. `docker-compose up` (much simpler than the docker commands before)
3. Go to localhost:8080 in a browser.  You should see a button.
4. Click the button

The text "Hello, World!" should then display.

**Comment by djpace14** [comment]
Ok. I will check later tonight after work. Sorry been busy with various tasks and errands today.

**Comment by djpace14** [comment]
Yes this all worked.
