### ISSUE TITLE
Create Player ID Webpage

### ISSUE THREAD

**Issue by djpace14** [smileydts/death-or-glory#8]
Enable input of player name.

**Comment by smileydts** [comment]
Suggested branch name: feature/dog-8-player-id-page

**Comment by djpace14** [comment]
git checkout -b feature/dog-8-player-id-page

As working make commits - git commit -m "some message"

Then when done do git push - make pull request

**Comment by smileydts** [comment]
In case you're interested, here's an [example ](https://chat.openai.com/share/0760fd0b-af6b-4f55-8ca2-f2313145309a) of how I do some very basic problem solving with ChatGPT without having it give me full answers straightaway
